groups:
  - name: all
    jobs:
      - compile_pxf
      - test_pxf_cli_gpdb5
      - test_pxf_cli_gpdb6

## ======================================================================
## ANCHORS
## ======================================================================
ccp_destroy_anchor: &ccp_destroy
  do:
  - put: terraform_gpdb
    resource: terraform
    params:
      action: destroy
      env_name_file: terraform_gpdb/name
      terraform_source: ccp_src/google/
    get_params:
      action: destroy

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.14

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
## RESOURCES
## ======================================================================
resources:

- name: pxf_tarball
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: pxf_artifacts/pxf_cli_test/latest/pxf.tar.gz

- name: gpdb5_src
  type: git
  source:
    branch: 5X_STABLE
    uri: {{gpdb-git-remote}}

- name: gpdb6_src
  type: git
  source:
    branch: 6X_STABLE
    uri: {{gpdb-git-remote}}

- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}

- name: pxf_src
  type: git
  source:
    branch: {{pxf-git-branch}}
    uri: {{pxf-git-remote}}
    #     paths:
    #     - cli
    #     - server/pxf-service/src/scripts
    #     - server/pxf-service/src/templates/tomcat/bin

- name: gpdb-pxf-dev-centos6
  type: docker-image
  source:
    repository: pivotaldata/gpdb-pxf-dev
    tag: centos6

- name: ccp-7
  type: docker-image
  source:
    repository: pivotaldata/ccp
    tag: 7

- name: bin_gpdb5_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{icw_green_bucket_gpdb5}}
    versioned_file: bin_gpdb_centos6/gpdb_branch_5X_STABLE/icw_green/bin_gpdb.tar.gz

- name: bin_gpdb6_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-resources-prod))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel6_x86_64.tar.gz

- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
    vars:
      project_id: {{google-project-id}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      bucket: {{tf-bucket-name}}
      bucket_path: {{tf-bucket-path}}

## ======================================================================
## JOBS
## ======================================================================
jobs:

- name: compile_pxf
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb-pxf-dev-centos6
  - task: compile_pxf
    image: gpdb-pxf-dev-centos6
    file: pxf_src/concourse/tasks/compile_pxf.yml
  - put: pxf_tarball
    params:
      file: pxf_artifacts/pxf.tar.gz

- name: test_pxf_cli_gpdb5
  max_in_flight: 2
  plan:
  - in_parallel:
    - get: ccp_src
    - get: gpdb_src
      resource: gpdb5_src
    - get: gpdb_binary
      resource: bin_gpdb5_centos6
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: ccp-7
    - get: gpdb-pxf-dev-centos6
  - put: terraform_gpdb
    resource: terraform
    params:
      action: create
      delete_on_failure: true
      generate_random_name: true
      terraform_source: ccp_src/google/
      vars:
        PLATFORM: centos7
        number_of_nodes: {{number_of_gpdb_nodes}}
        extra_nodes: 0
        segments_per_host: 3
        instance_type: n1-standard-4
        ccp_reap_minutes: 120
        standby_master: true
  - task: gen_gpdb_cluster
    input_mapping:
      terraform: terraform_gpdb
    file: ccp_src/ci/tasks/gen_cluster.yml
    image: ccp-7
    params:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-region}}
      BUCKET_PATH: {{tf-bucket-path}}
      BUCKET_NAME: {{tf-bucket-name}}
      PLATFORM: centos7
      CLOUD_PROVIDER: google
  - task: Initialize Greenplum
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: Setup PXF
    input_mapping:
      terraform: terraform_gpdb
      bin_gpdb: gpdb_binary
    file: pxf_src/concourse/tasks/install_pxf.yml
    image: ccp-7
    params:
      BUCKET_PATH: {{tf-bucket-path}}
      BUCKET_NAME: {{tf-bucket-name}}
      CLOUD_PROVIDER: google
      PLATFORM: centos7
      PXF_JVM_OPTS: {{pxf-jvm-opts}}
      SKIP_HADOOP_SETUP: true
  - task: test_pxf_cli
    input_mapping:
      bin_gpdb: gpdb_binary
    on_success:
      <<: *ccp_destroy
    image: gpdb-pxf-dev-centos6
    file: pxf_src/concourse/tasks/test_pxf_cli.yml
    params:
      PGPORT: {{pgport_gpdb5}}
      TARGET_OS: centos
      TARGET_OS_VERSION: 6

- name: test_pxf_cli_gpdb6
  max_in_flight: 2
  plan:
  - in_parallel:
    - get: ccp_src
    - get: gpdb_src
      resource: gpdb6_src
    - get: gpdb_binary
      resource: bin_gpdb6_centos6
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: ccp-7
    - get: gpdb-pxf-dev-centos6
  - put: terraform_gpdb
    resource: terraform
    params:
      action: create
      delete_on_failure: true
      generate_random_name: true
      terraform_source: ccp_src/google/
      vars:
        PLATFORM: centos7
        number_of_nodes: {{number_of_gpdb_nodes}}
        extra_nodes: 0
        segments_per_host: 3
        instance_type: n1-standard-4
        ccp_reap_minutes: 120
        standby_master: true
  - task: gen_gpdb_cluster
    input_mapping:
      terraform: terraform_gpdb
    file: ccp_src/ci/tasks/gen_cluster.yml
    image: ccp-7
    params:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-region}}
      BUCKET_PATH: {{tf-bucket-path}}
      BUCKET_NAME: {{tf-bucket-name}}
      PLATFORM: centos7
      CLOUD_PROVIDER: google
  - task: Initialize Greenplum
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: Setup PXF
    input_mapping:
      terraform: terraform_gpdb
      bin_gpdb: gpdb_binary
    file: pxf_src/concourse/tasks/install_pxf.yml
    image: ccp-7
    params:
      BUCKET_PATH: {{tf-bucket-path}}
      BUCKET_NAME: {{tf-bucket-name}}
      CLOUD_PROVIDER: google
      PLATFORM: centos7
      PXF_JVM_OPTS: {{pxf-jvm-opts}}
      SKIP_HADOOP_SETUP: true
  - task: test_pxf_cli
    input_mapping:
      bin_gpdb: gpdb_binary
    on_success:
      <<: *ccp_destroy
    image: gpdb-pxf-dev-centos6
    file: pxf_src/concourse/tasks/test_pxf_cli.yml
    params:
      PGPORT: {{pgport_gpdb6}}
      TARGET_OS: centos
      TARGET_OS_VERSION: 6
