platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpdb_src
- name: pxf_src
- name: bin_gpdb
- name: pxf_tarball
- name: ccp_src
- name: cluster_env_files
- name: terraform
- name: terraform_dataproc
  optional: true
- name: dataproc_env_files
  optional: true
- name: dataproc_2_env_files
  optional: true

params:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_DEFAULT_REGION:
  BUCKET_NAME:
  BUCKET_PATH:
  CLOUD_PROVIDER:
  IMPERSONATION: true
  INSTALL_GPHDFS: true
  SKIP_HADOOP_SETUP:
  KERBEROS: false
  PLATFORM:
  PXF_JVM_OPTS:

run:
  path: sh
  args:
  - -exc
  - |
    ccp_src/scripts/setup_ssh_to_cluster.sh || exit 1
    pxf_src/concourse/scripts/install_pxf.bash
